Chrezm/DRO-Client

courtroom.cpp
courtroom.h

Style similar to AO but not quite the same; also fixes a bug in parent branch with the internal records not being truncated.

Reimplement log truncation

---

aoapplication.h
courtroom.cpp
courtroom.h
datatypes.h
debug_functions.cpp
main.cpp
text_file_functions.cpp

This should fix most issues related the IC log, or at least I would hope so.

IcLog rework to fix lag + extra changes

---

lobby.cpp
lobby.h

Description now reads 'Connecting to' until connected+Player count hidden until successful connection

---

charselect.cpp
courtroom.cpp

+Explicitly notify the server of spectator choice

Reintroduce spectator button to char select

---

courtroom.cpp
courtroom_widgets.cpp

Readd notepad scrollbar if needed

Do not overwrite notepad text if no selected file

---

aoapplication.cpp
aoconfig.cpp
aoconfig.h
aoconfigpanel.cpp
aoconfigpanel.h
courtroom.cpp
courtroom.h
datatypes.h
res/ui/config_panel.ui

Add pending widgets to config panel
*always_pre
*chat_tick_interval
*music_change_log
Also fixed music_change_log having opposite behavior (logging only when it's False rather than only when True)

Missing config panel widgets

---

courtroom.cpp
courtroom.h
text_file_functions.cpp

Specific highlight characters may be turned on or off per theme.

Render (or not) specific highlight characters

---

courtroom.cpp
courtroom.h
emotes.cpp
packet_distribution.cpp

After changing/selecting character, the character's default position now appears in the position dropdown box.

Correct position on character change

---

aoapplication.cpp
aoapplication.h
aoconfig.cpp
aoconfig.h
aoconfigpanel.cpp
aoconfigpanel.h
courtroom.cpp
courtroom.h
courtroom_widgets.cpp
res/ui/config_panel.ui

Remove guard checkbox toggleable by /login, instead moving it as part of a 'Server alerts' option in the configuration panel

Guard to config panel

---

aoapplication.cpp
aoapplication.h
aoconfig.cpp
aoconfig.h
aoconfigpanel.cpp
aoconfigpanel.h
courtroom.cpp
courtroom_widgets.cpp
path_functions.cpp
res/ui/config_panel.ui
text_file_functions.cpp

* Added theme variant dropdown to the config panel
* Removed OOC command /variant

Variants revamped

---

aoapplication.h
aoblipplayer.cpp
aocharbutton.cpp
aocharmovie.cpp
aoemotebutton.cpp
aoevidencebutton.cpp
aoevidencedisplay.cpp
aoimage.cpp
aomovie.cpp
aoscene.cpp
aosfxplayer.cpp
aoshoutplayer.cpp
charselect.cpp
courtroom.cpp
courtroom.h
courtroom_widgets.cpp
evidence.cpp
file_functions.cpp
file_functions.h
path_functions.cpp
text_file_functions.cpp

HOLY SHIT WHY DID THIS PROVE MORE DIFFICULT THAT IT SHOULD HAVE BEEN

Fix Linux case-sensitivity issues, Attempt 2

---

courtroom.cpp

- fix `opus` file issues for #44

#44 opus-not-found

---

src/courtroom.cpp

* Music records to logs
* Removed needless code duplication

Music records

---

.gitignore
dronline-client.pro
include/aoapplication.h
include/aoconfig.h
include/aoconfigpanel.h
include/aoguiloader.h
include/aoimage.h
include/courtroom.h
include/file_functions.h
res/ui/config_panel.ui
src/aoapplication.cpp
src/aobutton.cpp
src/aocharmovie.cpp
src/aoconfig.cpp
src/aoconfigpanel.cpp
src/aoevidencebutton.cpp
src/aoevidencedisplay.cpp
src/aoguiloader.cpp
src/aoimage.cpp
src/aolabel.cpp
src/aomovie.cpp
src/aoscene.cpp
src/aosfxplayer.cpp
src/aoshoutplayer.cpp
src/courtroom.cpp
src/courtroom_widgets.cpp
src/file_functions.cpp
src/packet_distribution.cpp
src/path_functions.cpp
src/text_file_functions.cpp

Addresses #69
(Only review once requested, PR is in progress)

Gamemodes and time of day (#69)

---

src/courtroom.cpp

* FIX out of range assert failure

Fix out of range issues

---

src/courtroom.cpp

AOMovie->play takes in a file name, not a full directory

Fix clock looking for wrong file location to play animation

---

include/aoapplication.h
include/aoemotebutton.h
src/aobasshandle.cpp
src/aoemotebutton.cpp
src/emotes.cpp

* Removed AO2 'portion'
* Removed 'hovers' (it's undocumented so it's very unlikely anyone ever used it anyway)
* Added requested enhancements

Resolves #88

---

include/aoconfig.h
include/aoconfigpanel.h
res/ui/config_panel.ui
src/aoconfig.cpp
src/aoconfigpanel.cpp

* If enabled, autosave will automatically save config settings upon exiting (shutting down) the client.
- This allows the user to be aware of whatever the config settings will be saved or not automatically as well as providing visual feedback.
P.S. Could we finally **PLEASE** make it so that pull requests do not automatically try to go towards [elfmonster/AO2-Client](https://github.com/elfmonster/AO2-Client)? Thanks.

Introduced Autosave on ConfigPanel

---

include/courtroom.h
include/draudiostreamfamily.h
src/aoapplication.cpp
src/audio_functions.cpp
src/courtroom.cpp
src/draudiostream.cpp
src/draudiostreamfamily.cpp

* Fixed short audio files not playing properly.
* Tweaked the Disconnected from server notification to immediately stop all audio upon appearance

Fixed short audio issues and tweaks to disconnection popup

---

src/courtroom.cpp

* Added emote hiding hardcoded parameter

Added emote hiding

---

include/aosfxplayer.h
src/aosfxplayer.cpp
src/courtroom.cpp

Solves #137, stop all sound effects on a new message

---

include/aosfxplayer.h
src/aoevidencedisplay.cpp
src/aosfxplayer.cpp
src/courtroom.cpp
src/file_functions.cpp

Added character sound pathing to SfxPlayer

---

include/aoapplication.h
include/aocharmovie.h
include/aoemotebutton.h
include/aosfxplayer.h
include/aoshoutplayer.h
include/courtroom.h
include/datatypes.h
src/aocharmovie.cpp
src/aoemotebutton.cpp
src/aosfxplayer.cpp
src/aoshoutplayer.cpp
src/courtroom.cpp
src/emotes.cpp
src/packet_distribution.cpp
src/path_functions.cpp
src/text_file_functions.cpp

Added include option for char.ini

---

include/courtroom.h
src/courtroom.cpp
src/emotes.cpp

Make reloading themes not reset text cursor or emote

---

include/aoapplication.h
include/courtroom.h
include/lobby.h
src/aoapplication.cpp
src/aoconfig.cpp
src/courtroom.cpp
src/emotes.cpp
src/lobby.cpp
src/packet_distribution.cpp
src/path_functions.cpp
src/text_file_functions.cpp

Resolve #164
Very light optimization to reduce theme reloading.

Theme loading optimization

---

include/aoconfig.h
include/courtroom.h
src/aoapplication.cpp
src/aoconfig.cpp
src/courtroom.cpp
src/courtroom_widgets.cpp
src/emotes.cpp
src/packet_distribution.cpp

#161 - Ini-swap dropdown

---

include/aoapplication.h
include/courtroom.h
res/ui/config_panel.ui
src/courtroom.cpp
src/courtroom_widgets.cpp
src/packet_distribution.cpp

Tick rate & speed keywords

---

dronline-client.pro
include/courtroom.h
include/drtextedit.h
include/lobby.h
include/theme.h
src/charselect.cpp
src/courtroom.cpp
src/courtroom_widgets.cpp
src/emotes.cpp
src/evidence.cpp
src/lobby.cpp
src/theme.cpp

Resolve #178 
Also include:
- theme helper functions

Text alignment on fields

---

include/courtroom.h
src/aoconfig.cpp
src/charselect.cpp
src/courtroom.cpp
src/courtroom_widgets.cpp
src/emotes.cpp

Development into Master

---

include/aoapplication.h
src/aoapplication.cpp
src/main.cpp

Font loading

---

include/courtroom.h
src/courtroom.cpp
src/courtroom_widgets.cpp

Resolve #184
* Didn't add delta rework as of time of writing.

Tick Rate Optimization

---

include/aocharbutton.h
include/courtroom.h
src/aoapplication.cpp
src/aocharbutton.cpp
src/charselect.cpp
src/courtroom.cpp
src/courtroom_character.cpp
src/courtroom_widgets.cpp

* Ini-swapped character icon now shows in the bottom-right of the original character
* Clicking on the character we already have selected will reload the character itself
* Added tooltip to character icon

Ini-swap charselect tweaks

---

include/aoapplication.h
include/courtroom.h
res/ui/config_panel.ui
src/aoapplication.cpp
src/aoconfig.cpp
src/courtroom.cpp
src/courtroom_widgets.cpp
src/text_file_functions.cpp
src/theme.cpp

* Changed the minimum log line count to 1
* Disabled vertical text alignment
* Extra block no longer needed
* Cache text char formats for ic chatlog
* Added maybe_color for reading a color from ini

Improved IC chatlog performance

---

src/aomovie.cpp

AOMovie improvements

---

src/text_file_functions.cpp

* This just caused more issues than it solved, people should just fix their INIs instead of being lazy with it. Thanks.

Removed emote filter

---

include/commondefs.h
include/courtroom.h
include/theme.h
src/aonotearea.cpp
src/commondefs.cpp
src/courtroom_widgets.cpp
src/theme.cpp

* Rename internal function referencing setting dropdown stylesheets to setting stylesheets, as we use that function for widgets other than dropdowns
* Add support for two widgets getting stylesheets: the IC showname box and the OOC username box. I'm still unsure about the name I chose to expect users put in the stylesheets file.

Stylesheets improvements

---

include/courtroom.h
src/courtroom.cpp
src/courtroom_sfx.cpp
src/courtroom_widgets.cpp

Separate area and music listing

---

src/courtroom.cpp

Fix highlight color leak on new message

---

include/aoemotebutton.h
src/aoemotebutton.cpp

Emote buttons are now resized smoothly

---

src/aocharmovie.cpp

Added emote blacklist

---

.github/workflows/build-all.yml
.github/workflows/ubuntu-515.yml
src/theme.cpp

We should be moving to an LTS version of Qt.

Update workers to Qt 5.15

---

include/draudiostream.h
src/draudiostream.cpp

Add music looping

---

src/courtroom.cpp
src/version.cpp

Backslash now prevents highlight color characters from activating/hiding 

---

dronline-client.pro
include/log.h
src/aoapplication.cpp
src/charselect.cpp
src/courtroom.cpp
src/log.cpp
src/main.cpp
src/version.cpp

Resolves #256 
It also keeps outputting messages via standard Qt protocol.

Redirect debug logs to file 

---

.github/workflows/build-all-merge-master.yml

This should help iron out potential non-merge conflict errors that would result from merging a PR.

Add action to also build master merged onto PR.

---

src/courtroom.cpp
src/datatypes.h

Added showname to MS packet

---

src/courtroom_widgets.cpp

Added chat message placeholder instructions

---

res/ui/config_panel.ui
src/aoapplication.cpp
src/aoapplication.h
src/aoconfig.cpp
src/aoconfig.h
src/aoconfigpanel.cpp
src/aoconfigpanel.h
src/courtroom.cpp
src/courtroom.h
src/courtroom_widgets.cpp
src/datatypes.h
src/server_socket.cpp

This allows users to identify two players using the same display name.

Added client Id to MS packet

---

src/courtroom.cpp
src/courtroom.h

Reworked music behavior

---

src/aoapplication.h
src/courtroom.cpp
src/server_socket.cpp

Resolve #240 
```
FA[#Area 1#...]#%
```
A list of strings representing area names.
```
FM[#song.wav#...]#%
```
A list of strings representing song filenames.

Added FA and FM packet

---

dronline-client.pro
src/aoapplication.h
src/commondefs.cpp
src/commondefs.h
src/courtroom.cpp
src/courtroom.h
src/drposition.cpp
src/drposition.h
src/drscenemovie.cpp
src/drscenemovie.h
src/path_functions.cpp

Overhauled position file seeking

---

src/courtroom.cpp
src/courtroom.h

This should resolve the issue of which a background does not have a `positions.ini` file to read from.

Added legacy background support

---

src/courtroom_widgets.cpp
src/theme.cpp
src/theme.h
src/version.cpp

Added `*_anim_play_once` setting to theme config ini

---

src/courtroom_character.cpp

Implement outgoing FS packet
