courtroom.cpp
Add warnings for empty OOC name/message when trying to talk in the OOC chat. A client warning appears if the message is empty. Otherwise, an input dialog box appears if OOC name is empty; whatever name is put there is automatically put in the OOC name box.
=> Chat warnings

aocharbutton.cpp, aocharbutton.h, charselect.cpp, courtroom.cpp, courtroom.h, courtroom_widgets.cpp, emotes.cpp
- Fixed emotes and char_select not resizing properly after theme reloading
- Added small QOL: current selected theme is kept in memory after reloading the theme
=> Resizing of emotes and char_select

aocharmovie.cpp, aocharmovie.h, aoevidencedisplay.cpp, aoimage.cpp, aopixmap.cpp, aopixmap.h, aoscene.cpp, aoscene.h, courtroom.cpp, courtroom_widgets.cpp
Previously if a reload theme changed viewport, the old assets would display on screen until another person spoke IC, which led either to awkwardly hidden assets (due to viewport size shrinking) or awkwardly bordered assets (due to viewport size increasing)
=> Update character, background and desk on reload theme changing resolution

courtroom.cpp, courtroom.h
In comparison to the original marking PR, the following changes were made:
* Instead of checking if the old selected row is null, we check if the old selected row index is still -1. Doing the former led to crashes.
* The selected SFX is dynamially lit up.
* Some previously missed lines from the Linux compat were also fixed.
* `play_sfx` only tried playing the extension, fixed to play the full filepath instead.
**Since there is a default highlighting on Linux, I'd like if either of you could test this on Windows.**
I can see it sorta flash-up behind the OS-granted highlighting, but I'd like to make sure.
=> Add light-up to selected SFX list item

courtroom.cpp, courtroom.h, courtroom_widgets.cpp
This PR makes it so that instead of dynamically doing string wizardly to add a manual checkbox to the entries in the mute list, it uses Qt's built-in support for checkbox items in QListWidgets.
The functionality is otherwise the same.
=> Replace "[X]" with checkboxes in the mute list

Attorney_Online_remake.pro, aoapplication.h, packet_distribution.cpp
Fixes #49 .
The version in the project file is for internal use only, changing it does nothing.
The actual meaningful change comes from changing the version number in `aoapplication.h`.
=> Change version and software to DRO 1.0.0

aoevidencebutton.cpp, aoevidencebutton.h
Removed the two functions that blast the entire compilation process with warnings.
They not only used the wrong parameter types (should have been `QDragEnterEvent` and `QDragLeaveEvent` instead of `QMouseEvent` in both places), they also did nothing, so why keep them around.
=> Clean up build warnings

courtroom.cpp, courtroom.h
Pretty simple PR, just add support for shownames in system messages, and makes a check as to not overwrite the empty showname for system messages.
Fixes #45 .
=> Add showname support for system IC messages

aocharmovie.cpp, aomovie.cpp, aoscene.cpp, courtroom.cpp
There were a select few places where the case sensitive path version wasn't grabbed, resulting in always missed path lookups on Linux.
Good example is `base/characters/Tenko_HD/disappointed.png`.
The client looks for a case-insensitive `Disappointed`, without extension and with capitalisation, fails, then case-sensitively looks it up with various extensions -- which all fail, because the file itself is uncapitalised.
=> Fix missing case sensitive path getting in places

aonotepicker.cpp
Adds the ability to close notes by clicking the note selection button again, and fixes a bug where you could still edit notes after deleting them off the list, if you had them selected.
This feature keeps the "ephemeral storage" function for the notepad if there is no selected note at the moment.
So you could open a note, edit it, close it, keep the text from it, edit the text (without editing the note), and then reopen the note, discarding your previous edits while no note was open.
Closes #46 .
=> Add ability to close notes through deselecting and deleting

src/lobby.cpp
Adds the current DRO developers to the about window.
Also modifies the About window to be more like Vanilla's, and to actually use the Qt-given About window default.
The translation strings are left in the messages purposefully, in case we want to supply translations later (and because being able to add arguments this way was convenient).
Closes #48 .
=> Add DRO devs to about window

.gitignore, src/aoconfig.cpp, src/lobby.cpp
It is possible to trigger the DRO 'base not found' error if the current theme folder does not exist, which can be tricky to decide has happened with an error message that does not describe it. This PR changes the wording to include the current theme
=> Improve 'base not found' launch error to account for missing theme

.gitignore, src/courtroom.cpp
*Replace null chars with proper empty strings when adding records in colon mode. Null chars prevented Windows users from copying text that spanned multiple messages in the IC log due to the null char signaling an early end to the text.
*System messages sent in newline mode now include the characteristic new line.
=> IC Chatlog fixes

include/aotimer.h, src/aotimer.cpp
* Optimize timer restarts to take advantage of QT's better automatic restarts. Manual restarts now only occur if the firing interval changed or does not match the firing timer's interval (which can happen if the timer is paused midstep).
* Prevent the timer from abnormally starting if it receives an order to update its firing interval while it is paused.
* Make the default time be 00:00
=> Timer improvements

dronline-client.pro, include/aoapplication.h, include/courtroom.h, src/courtroom.cpp, src/packet_distribution.cpp
This PR is done in cooperation with some additional server changes. A server that sends "ackMS" as part of the FL packet promises it will send an "ackMS" packet to a client as soon as it acknowledges it has properly received an IC message from the client and that it will do something (server won't reject the message because, for example, client sent the same message twice), but *before* it sends an MS packet. That way, a client that recognizes the ackMS can use such a packet as an instruction to reset UI after having successfully sent an IC message. If the server does not send "ackMS", behavior is the same as before (reset UI if IC message's char_id matches the client's).
The reason why we need to perform this extra step is to allow the server to send messages with the same character as …
=> Implement ackMS packet recognition to reset UI after server acknowledges client sent IC message

dronline-client.pro, include/aoconfig.h, include/aoconfigpanel.h, include/datatypes.h, include/draudio.h, include/draudiodevice.h, include/draudioengine.h, include/draudioengine_p.h, include/draudioerror.h, include/draudiostream.h, include/draudiostreamfamily.h, res/ui/config_panel.ui, src/aoconfig.cpp, src/aoconfigpanel.cpp, src/draudio.cpp, src/draudiodevice.cpp, src/draudioengine.cpp, src/draudioengine_p.cpp, src/draudioerror.cpp, src/draudiostream.cpp, src/draudiostreamfamily.cpp, src/main.cpp
DRAudioEngine has been updated to automatically pick a device and can be provided a favorite device.
If a favorite device has been designed, DRAudioEngine will attempt to transfert all currently playing sounds to the favorite device of choice.
Otherwise, it will attempt to pick the designated audio device chosen by the OS.
Finally, If there is no designated audio device, it will pick the first one available.
Finally, if there are no devices available the client will simply prevent audio from playing and will report the issue in the console.
DRAudioEngine will always attempt to have an audio device active. As long as one is enabled within the OS, it will attempt its best to use it. Failing this, sounds will simply be disabled and won't be able to play until an appropriate device is …
=> Resolves #119, added audio-device system

include/aoconfig.h, include/aoconfigpanel.h, include/courtroom.h, include/datatypes.h, res/ui/config_panel.ui, src/aoconfig.cpp, src/aoconfigpanel.cpp, src/courtroom.cpp, src/courtroom_widgets.cpp
Resolve #144, resolve #87
Added personal highlight color for names, this will look for the color (`ic_chatlog_selfname_color`) in `courtroom_fonts.ini`.
Failing that, it will simply use the name color (`ic_chatlog_showname_color`). If neither are set, it will use the default color.
The self-identification is done by comparing the message's chr_id to the one we currently are.
=> Self-identification highlight coloring

include/courtroom.h, include/datatypes.h, src/courtroom.cpp, src/courtroom_widgets.cpp, src/emotes.cpp
A few methods that are run in ackMS update sprites that need not be updated. This causes needless delay in processing messages, given there is file I/O involved. This PR makes it so that these methods are replaced with methods that target specifically only what needs to be redrawn.
=> Remove needless image setting in ackMS

include/aoapplication.h, include/courtroom.h, include/datatypes.h, include/drtextedit.h, src/aoapplication.cpp, src/aocharmovie.cpp, src/courtroom.cpp, src/courtroom_widgets.cpp, src/drtextedit.cpp, src/emotes.cpp, src/path_functions.cpp, src/text_file_functions.cpp
* Reduces calls to horizontal alignment to only when the number of blocks change as opposed to every time text changes (which is good enough for text editors where we only do appends and sets, which is the use case for DRO)
* Allows turning off/on automatic alignment (which helps prevent frivolous computation when doing batch operations involving text editors, like reloading the log)
* Makes chat ticks only start appearing after rendering a sprite (which helps prevent having the first character of an IC message render, then the sprite, then the remaining characters render, which gives the illusion of lag)
* Removes unused text_delay_interval function
* Makes attempts to open preanimation "-", " - " (typically used in DRO to indicate no preanimation) fail immediately rather than as part of …
=> Optimize alignment changes and rendering of IC messages

include/aoemotebutton.h, include/courtroom.h, src/aoemotebutton.cpp, src/courtroom.cpp, src/courtroom_widgets.cpp, src/emotes.cpp
* Emote preview size can be changed by adding a `courtroom_design.ini` entry that list the position & size of `emote_preview` widget
* Emote and iniswap dropdowns are now disabled instead of hidden when spectating
=> Added emote preview, emote and iniswap visibility changes

.github/workflows/build-all.yml
The official release of the plugin is based on Qt 5.14.1, incompatible with the older versions of Qt (specifically the one from Ubuntu 20.04)
This will always build the plugin based on the latest version of Ubuntu 20.04[at the time of writing] (or whatever current version is defined by the Github CLI)
=> Build QtApng plugin instead of downloading

include/courtroom.h, src/courtroom.cpp, src/courtroom_character.cpp
If `CONTENT.txt` is present within the base folder of the character, it will read the file and send a slash command (`files_set`) to notify the server of the current character content link.
=> Added character content url

include/aoapplication.h, include/aoconfig.h, include/aoconfigpanel.h, include/commondefs.h, include/courtroom.h, include/datatypes.h, src/aoapplication.cpp, src/aoconfig.cpp, src/aoconfigpanel.cpp, src/aoscene.cpp, src/commondefs.cpp, src/courtroom.cpp, src/path_functions.cpp, src/server_socket.cpp
* Implemented #210
* Renamed a couple `AOConfig` methods and variables
* Removed `get_background_path` from `Courtroom`
This had a severe case of circling around for no good reason. `AOApplication` -> `Courtroom` -> `AOApplication` for background pathing. This has been removed.
=> Implemented #210, miscellaneous changes

dronline-client.pro, include/version.h, src/version.cpp
Useful to internally mark development client versions (e.g. "b1").
Also bumped to 1.1.0-b1.
=> Add post-version to version identifiers

include/drmovie.h, src/courtroom.cpp, src/drmovie.cpp, src/drscenemovie.cpp
This is useful for background folders where by design all positional images are the same, as it reduces 5x the amount of files required for such a background folder.
=> Use witness background/desk if positional background/desk unavailable

include/courtroom.h, include/lobby.h, include/theme.h, src/aoapplication.cpp, src/charselect.cpp, src/courtroom.cpp, src/courtroom_widgets.cpp, src/lobby.cpp, src/theme.cpp
Steps of bug.
1. Join server with theme A.
2. Once logged in, switch to theme B, whose `courtroom` size is of different size from theme A
3. Maximize DRO
4. Unmaximize DRO
5. Now DRO has the size of courtroom from theme A rather than B.
=> Fix unmaximizing giving wrong size if player launched with theme of different size to current one

dronline-client.pro, res/ui/config_panel.ui, src/aoapplication.cpp, src/aoapplication.h, src/aoconfig.cpp, src/aoconfig.h, src/aoconfigpanel.cpp, src/aoconfigpanel.h, src/courtroom.cpp, src/debug_functions.cpp, src/debug_functions.h, src/lobby.cpp, src/master_socket.cpp, src/server_socket.cpp
Resolve #283, #284
As issued, this removes multiple checks that the server should be assumed to be compatible with. If the server is not considered compatible, then it will warn the user as they attempt to join said server.
New argument(s): `v110`
`v110` The version that the server needs to support.
=> Assume v110 server compatible

src/lobby.cpp, src/lobby.h
* When a filter is toggled on, it will now only show the intended category rather than the opposite.
=> Changed the filter server buttons

src/courtroom.cpp, src/drcharactermovie.cpp, src/drmovie.cpp, src/drmovie.h, src/drscenemovie.cpp
This should resolve the issue of background pictures either being too large in width or height, now dynamically pick either or depending on what would fit the viewport best.
=> Added dynamic scaling to animated images

src/courtroom.cpp, src/draudiotrackmetadata.cpp, src/draudiotrackmetadata.h
This prevents the issue of having to have filenames that do not have `[ ] /`
=> Change syntax of audio track loop points files so file name is a key
